### PR TITLE
Fix bug TapsScreen

### LINKED ISSUE #154: bug: No trip selected when not allowing permissions from settings
To reproduce:
Photos permissions must be on
Voyageur -> select a trip
Go to settings -> apps -> Voyager -> permisions -> Photos -> don't allow
Go back to Voyageur
No trip selected
https://github.com/user-attachments/assets/f6fa6dfb-329b-413c-936c-e3dd23742d1b

### PR DESCRIPTION
**Pull request by BogdanCDev**
## Summary

This pull request fixes a bug in the TopTabs composable where an error occurred if the selected trip was null after modifying photo permissions. The update ensures that the app navigates back to the "Overview" screen if there is no selected trip, improving error handling and user experience. This is a bug fix aimed at gracefully handling cases where a trip may be null.

## Changes

- **Screens/UI:** Updated the TopTabs composable to check if the selected trip is null. If null, it now navigates back to the "Overview" screen using NavigationActions.
- **Bug Fixes/Improvements:** Addresses the issue where modifying photo permissions could cause a null trip error in TopTabs. This fix ensures a smooth user experience when permissions are modified.
## Checklist

Ensure all / most of these are checked before the pull request is submitted.
- [X] This PR resolves #154 

##  Related Issues/Tickets

Closes #154 

## Screenshots

https://github.com/user-attachments/assets/84029123-eded-4035-9d7b-f747721fa094

### CODE REVIEW

File: app/src/main/java/com/android/voyageur/ui/trip/Tabs.kt [hunk 1]
```diff
@@ -28,13 +29,19 @@ fun TopTabs(tripsViewModel: TripsViewModel, navigationActions: NavigationActions
...
+  // Check if the selected trip is null and navigate to "Overview" if true
+  if (trip == null) {
+    navigationActions.navigateTo(Route.OVERVIEW)
+    return
+  }
 
   // Column for top tabs and content
   Column(modifier = Modifier.testTag("topTabs")) {
-    TopBarWithImage(trip, navigationActions)
+    TopBarWithImage(trip!!, navigationActions)
```
Comment (ioanajianu) [inline app/src/main/java/com/android/voyageur/ui/trip/Tabs.kt:43]: instead of using trip!! everywhere let's do something like 
val selectedTrip = trip!! just once.

File: app/src/main/java/com/android/voyageur/ui/trip/Tabs.kt [hunk 2]
```diff
@@ -28,13 +29,19 @@ fun TopTabs(tripsViewModel: TripsViewModel, navigationActions: NavigationActions
...
   var selectedTabIndex by remember { mutableIntStateOf(0) }
 
-  val trip =
-      tripsViewModel.selectedTrip.value
-          ?: return Text(text = "No trip selected. Should not happen", color = Color.Red)
+  // Collect selectedTrip as state to avoid calling .value directly in composition
+  val trip by tripsViewModel.selectedTrip.collectAsState()
+
+  // Check if the selected trip is null and navigate to "Overview" if true
+  if (trip == null) {
```
Comment (ioanajianu) [inline app/src/main/java/com/android/voyageur/ui/trip/Tabs.kt:36]: can we make a function to handle this case? I think we can use it in other parts of the code where we assume that the trip is not null

**Review by ioanajianu — APPROVED** [review]
Thanks Bogdan for quickly fixing this! 
I commented on just a few things, otherwise LGTM

File: app/src/main/java/com/android/voyageur/ui/trip/Tabs.kt (hunk 1 above)
Comment (BogdanCDev) [reply app/src/main/java/com/android/voyageur/ui/trip/Tabs.kt]: Thank you for your suggestion! I've implemented the changes as recommended.
