### PR TITLE
fix behavior when selecting only the date

### LINKED ISSUE #132: Fix behavior of add activity when selecting only the date
Right now when an activity is created with a date but without the time it appears to be on the first of January. Instead it should appear on that day with the hours 00:00 - 23:59

### LINKED ISSUE #134: fix behavior of add activity when selecting only start time/end time
Right now the start time and end time default to 00:00 if they're not set by the user.
This creates issues when the user selects only the start time: the activity starts at 10:00 for example, but ends at 00:00.
Instead, let's set the start time to default to 00:00, and the end time to 23:59. This can also be used to set the time when we select only the date.
Also, I think that selecting only the endTime is not very intuitive, so let's not allow the user to select an endTime without selecting a startTime first.

### PR DESCRIPTION
**Pull request by mirceagavrizi**
## Summary

When creating an activity, if you selected just the date and no startTime/endTime it was creating the activity at timestamp(0, 0). Now, it is created at the specified date (at midnight).
If not selected, set default startTime to 00:00 and endTime to 23:59. Moreover, we decided that you cannot have activities created just with endTime, but you can have activities created only with a startTime.

## Changes

- **Bug Fixes/Improvements:** 
- #132 
- #134 

## Checklist

Ensure all / most of these are checked before the pull request is submitted.
- [x] This PR resolves #132 .
- [x] This PR resolves #134 .  
- [ ] Tests have been added for new functionality.
- [ ] Screenshots or UI changes have been attached (if applicable).
- [ ] Documentation has been updated (if applicable).

##  Testing

Explain how this feature was tested and what kind of testing (unit, integration, UI) has been done. Mention platforms or configurations used for testing.
- **Manual Testing:**
    - [x] Tested on emulator / physical device.
- **Unit Tests**
    - [ ] Added units tests for this

If you haven't added tests, please create a new issue and assign it.

##  Related Issues/Tickets

Closes #132 
Closes #134

### CODE REVIEW

**Review by ioanajianu — CHANGES_REQUESTED** [review]
Hey Mircea, thanks for implementing this change. Indeed now activities with only the date selected should appear not as a draft, but with a date assigned and lasting from 00:00 to 00:00. 
However I was thinking that it might be better to assign it the time interval 00:00 - 23:59, as it can be interpreted as an activity that lasts the whole day. 
Also, could you please fix in this PR the issue with the time #134 , they are related (they both need the 00:00. 23:59 time defaults).

Also, what do you think of displaying a toast if the user selects only a date? Something like "No times selected, defaults to 00:00-23:59"
Or if only the end time isn't selected, something like "No end time selected, defaults to 23:59".
I think those would be useful for the user since it's not very intuitive what happens in these scenarios

File: app/src/main/java/com/android/voyageur/ui/trip/AddActivity.kt [hunk 1]
```diff
@@ -130,6 +151,14 @@ fun AddActivityScreen(tripsViewModel: TripsViewModel, navigationActions: Navigat
       return
     }
 
+    if (startTime == null && endTime == null)
+        Toast.makeText(context, "No times selected, defaults to 00:00 - 23:59", Toast.LENGTH_SHORT)
+            .show()
```
Comment (ioanajianu) [inline app/src/main/java/com/android/voyageur/ui/trip/AddActivity.kt:156]: This toast now gets displayed even when we create a draft (with both startTime and endTime 0,0)
Please make sure these toasts get displayed only when we have a date.

Also, a toast saying "No date assigned, created as draft" if we do not assign a date would be nice to have

**Review by ioanajianu — APPROVED** [review]
Thanks Mircea for implementing the changes I suggested!
I have nothing more to add, good work! LGTM!
