### PR TITLE
fix: log in layout and logic

### LINKED ISSUE #349: improve login screen and login button and change logo
This issue aims to improve the LogIn Screen of the app by:
- Changing the LogIn button to adapt to whether the user is in Dark Mode/Light Mode (currently, the button is always white).
- Changing the logo of the app with a representative one.

### PR DESCRIPTION
**Pull request by eleonoraka**
## Summary

This PR fixes the Login screen by correcting the width of the login button and by showing the screen only if the user is not logged in yet.

## Changes

- **Screens/UI:** 
Login: reduced button size; screen logic as mentioned above
- **Bug Fixes/Improvements:**
Closes #349

## Checklist

Ensure all / most of these are checked before the pull request is submitted.
- [x] This PR resolves #349
- [ ] Tests have been added for new functionality.
- [ ] Screenshots or UI changes have been attached (if applicable).
- [x] Documentation has been updated (if applicable).

##  Testing

Explain how this feature was tested and what kind of testing (unit, integration, UI) has been done. Mention platforms or configurations used for testing.
- **Manual Testing:**
    - [ ] Tested on emulator / physical device.
- **Unit Tests**
    - [ ] Added units tests for this

Note: no tests have been added since no big changes have been made

##  Related Issues/Tickets

Closes #349

### CODE REVIEW

File: app/src/main/java/com/android/voyageur/ui/authentication/SignIn.kt [hunk 1]
```diff
@@ -40,23 +39,61 @@ import com.google.firebase.auth.auth
...
+    }
+  }
+
+  if (user == null) {
+    SignInScreen(navigationActions)
+  }
+}
+
 @Composable
 fun SignInScreen(navigationActions: NavigationActions) {
```
Comment (mirceagavrizi) [inline app/src/main/java/com/android/voyageur/ui/authentication/SignIn.kt:81]: Could you make the screen scrollable, e.g. if I have my phone in landscape I can't connect to the app.

File: app/src/main/java/com/android/voyageur/ui/authentication/SignIn.kt [hunk 2]
```diff
@@ -40,23 +39,61 @@ import com.google.firebase.auth.auth
...
 import kotlinx.coroutines.tasks.await
 
+@Composable
+private fun rememberFirebaseAuthLauncher(
+    onAuthComplete: (AuthResult) -> Unit,
+    onAuthError: (ApiException) -> Unit
+): ManagedActivityResultLauncher<Intent, ActivityResult> {
+  val scope = rememberCoroutineScope()
+
+  return rememberLauncherForActivityResult(ActivityResultContracts.StartActivityForResult()) {
```
Comment (mirceagavrizi) [inline app/src/main/java/com/android/voyageur/ui/authentication/SignIn.kt:49]: Also the line coverage is a bit low as this part is not covered.

Comment (eleonoraka) [reply app/src/main/java/com/android/voyageur/ui/authentication/SignIn.kt:49]: I agree with you on the coverage, however it is really difficult to test these structures with Mockito. Could we leave this be? Since this is a relatively short piece of code and it would not really impact the global coverage

**Review by mirceagavrizi — APPROVED** [review]
Thank you for implementing my suggestions and great job overall!
