### PR TITLE
fix: activity date is between trip's dates

### LINKED ISSUE #141: Fix Activity date in Add Activity screen to check the activity date within the trip dates

### PR DESCRIPTION
**Pull request by mirceagavrizi**
## Summary

Cannot create an activity if the date is not between the start date and end date of the trip (included).

## Changes

- **Bug Fixes/Improvements:** Solves #141 

## Checklist

Ensure all / most of these are checked before the pull request is submitted.
- [x] This PR resolves #141 .
- [ ] Tests have been added for new functionality.
- [ ] Screenshots or UI changes have been attached (if applicable).
- [ ] Documentation has been updated (if applicable).

##  Testing

Explain how this feature was tested and what kind of testing (unit, integration, UI) has been done. Mention platforms or configurations used for testing.
- **Manual Testing:**
    - [x] Tested on emulator / physical device.
- **Unit Tests**
    - [ ] Added units tests for this

If you haven't added tests, please create a new issue and assign it.

##  Related Issues/Tickets

Closes #141 

## Recording

https://github.com/user-attachments/assets/a89a6644-a7d8-4011-b3d2-7fbfae2d6355

### CODE REVIEW

File: app/src/main/java/com/android/voyageur/ui/trip/AddActivity.kt [hunk 1]
```diff
@@ -84,12 +79,27 @@ fun AddActivityScreen(tripsViewModel: TripsViewModel, navigationActions: Navigat
 
     val today = normalizeToMidnight(Date())
     val dateNormalized = activityDate?.let { normalizeToMidnight(Date(it)) } ?: Date(0)
+    val selectedTrip = tripsViewModel.selectedTrip.value!!
```
Comment (ioanajianu) [inline app/src/main/java/com/android/voyageur/ui/trip/AddActivity.kt:82]: Here instead of asserting it's non null, wdyt of adding a more specific error like in the Tabs screen:
`   val selectedTrip =
      tripsViewModel.selectedTrip.value
          ?: return Text(text = "No trip selected. Should not happen", color = Color.Red)`
This way it's easier to track down than a NullPointerException

File: app/src/main/java/com/android/voyageur/ui/trip/AddActivity.kt [hunk 2]
```diff
@@ -84,12 +79,27 @@ fun AddActivityScreen(tripsViewModel: TripsViewModel, navigationActions: Navigat
...
+
+    if (activityDate != null &&
+        (dateNormalized.after(normalizeToMidnight(selectedTrip.endDate.toDate())) ||
+            dateNormalized.before(normalizeToMidnight(selectedTrip.startDate.toDate())))) {
+      Toast.makeText(
+              context, "The activity date is not within the trip's dates", Toast.LENGTH_SHORT)
```
Comment (ioanajianu) [inline app/src/main/java/com/android/voyageur/ui/trip/AddActivity.kt:88]: nit: What do you think of the Toast message being "Please select a date within the trip's scheduled dates" instead? Up to you

**Review by ioanajianu — COMMENTED** [review]
Thanks for fixing this, Mircea!
Except for the 2 comments I have nothing to add, it looks good! I'll let Andreea give you the approval 
Just one thing: I find it useful to have screen recordings/screenshots to PR descriptions, even if it's just a bugfix, it helps me remember quickly what I worked on. If you think it would be useful to you or other teammates, consider adding those to future PRs :)

File: app/src/main/java/com/android/voyageur/ui/trip/AddActivity.kt (hunk 1 above)
Comment (ioanajianu) [reply app/src/main/java/com/android/voyageur/ui/trip/AddActivity.kt:82]: Actually, since we call Add Activity within a trip anyway, wdyt of sending the trip as a parameter instead of calling `tripsviewmodel.selectedTrip`?

File: app/src/main/java/com/android/voyageur/ui/trip/AddActivity.kt (hunk 2 above)
Comment (mirceagavrizi) [reply app/src/main/java/com/android/voyageur/ui/trip/AddActivity.kt:88]: Indeed, I think your toast suggestion is more user friendly, I'll change it.

File: app/src/main/java/com/android/voyageur/ui/trip/AddActivity.kt (hunk 1 above)
Comment (mirceagavrizi) [reply app/src/main/java/com/android/voyageur/ui/trip/AddActivity.kt:82]: You're right, it's better to take all cases into consideration.

Comment (ioanajianu) [reply app/src/main/java/com/android/voyageur/ui/trip/AddActivity.kt:82]: I agree, if all goes as expected, the selected trip should never be null, so I'm not strongly against leaving this as is. Up to you. In the future please document assumptions like these.

Comment (1andreea26) [reply app/src/main/java/com/android/voyageur/ui/trip/AddActivity.kt:82]: I tend to agree with Ioana on this, I think the way she suggested is a bit more elegant. However, I leave it up to you as well!

File: app/src/main/java/com/android/voyageur/ui/trip/AddActivity.kt [hunk 3]
```diff
@@ -84,12 +79,27 @@ fun AddActivityScreen(tripsViewModel: TripsViewModel, navigationActions: Navigat
...
+          .show()
+      return
+    }
 
     if (activityDate != null && dateNormalized.before(today)) {
       Toast.makeText(context, "The activity date cannot be in the past", Toast.LENGTH_SHORT).show()
       return
     }
 
+    if (startTime == null && endTime != null) {
```
Comment (1andreea26) [inline app/src/main/java/com/android/voyageur/ui/trip/AddActivity.kt:98]: I've noticed you have a lot of if conditions like this which throw toasts, I think it would improve code clarity if you structured them with a _when_ condition.

**Review by 1andreea26 — CHANGES_REQUESTED** [review]
Thanks for fixing this issue! I have 2 quick suggestions to make:
1. It would be great to include a test which checks that the user cannot submit with a date in the past.
2. In the future, please try to add some comments and try to be a bit more concise (I'm referring to the ifs in your case),  to improve code readability.

File: app/src/main/java/com/android/voyageur/ui/trip/AddActivity.kt (hunk 3 above)
Comment (BogdanCDev) [inline app/src/main/java/com/android/voyageur/ui/trip/AddActivity.kt:98]: Consider adding a validation to ensure that startTime is earlier than endTime, in order to prevent users from accidentally setting an invalid time range, which could lead to unexpected behavior or confusion.

File: app/src/main/java/com/android/voyageur/ui/trip/AddActivity.kt [hunk 4]
```diff
@@ -84,12 +79,27 @@ fun AddActivityScreen(tripsViewModel: TripsViewModel, navigationActions: Navigat
 
     val today = normalizeToMidnight(Date())
     val dateNormalized = activityDate?.let { normalizeToMidnight(Date(it)) } ?: Date(0)
+    val selectedTrip = tripsViewModel.selectedTrip.value!!
+
+    if (activityDate != null &&
+        (dateNormalized.after(normalizeToMidnight(selectedTrip.endDate.toDate())) ||
+            dateNormalized.before(normalizeToMidnight(selectedTrip.startDate.toDate())))) {
```
Comment (BogdanCDev) [inline app/src/main/java/com/android/voyageur/ui/trip/AddActivity.kt:86]: Consider normalizing selectedTrip.startDate and selectedTrip.endDate before the conditional check. This will enhance code readability by reducing redundant calls to normalizeToMidnight and make the date comparison logic more straightforward.

Comment (BogdanCDev) [reply app/src/main/java/com/android/voyageur/ui/trip/AddActivity.kt:86]: Also, following Andreea's and Ioana's comments, you could add a null check for selectedTrip before accessing its properties. This will prevent potential NullPointerException errors and ensure the code handles cases where selectedTrip may be null gracefully. I'll also leave the final decision up to you.

File: app/src/main/java/com/android/voyageur/ui/trip/AddActivity.kt (hunk 3 above)
Comment (mirceagavrizi) [reply app/src/main/java/com/android/voyageur/ui/trip/AddActivity.kt:98]: @BogdanCDev See https://github.com/swent-t16/Voyageur/blob/fix/activity-date-between-trip-dates/app/src/main/java/com/android/voyageur/ui/trip/AddActivity.kt#L157-L162

**Comment by mirceagavrizi** [comment]
As I previously mentioned, there is no possible way to end up in this screen without going through a valid trip. The `selectedTrip` field will always be set and there is no point in displaying an error message. Also if we change this behavior all the tests will need to be updated and that is beyond the scope of this pull request. If still feel like there is a need to change this in the future, please create a ticket for it.

File: app/src/main/java/com/android/voyageur/ui/trip/AddActivity.kt (hunk 3 above)
Comment (mirceagavrizi) [reply app/src/main/java/com/android/voyageur/ui/trip/AddActivity.kt:98]: Good idea, I made the changes.

**Comment by 1andreea26** [comment]
Thanks for improving the readability! I will approve this as you've considered the suggestions made by everyone, but in the future it could be great to comment the code to improve it even further!

**Review by 1andreea26 — APPROVED** [review]
Thanks for improving the readability! I will approve this as you've considered and modified the suggestions made by everyone, but in the future it could be great to comment the code to improve it even further!
