### PR TITLE
Fix/places api efficient fetching

### LINKED ISSUE #194: Fix places api cost

### PR DESCRIPTION
**Pull request by apana03**
## Summary

This PR solves an issue concerning high api costs due to testing after M2 deliverable. To solve that, in the userSearch we only display details that can be fetched for free and when the users clicks on a certain place the rest of the details will be fetched, this will allow us to not exceed the free credits for the api and the usage will not cost.

## Changes

- **Models:** In the PlacesViewModel when selecting an element we fetch the remaining details.
- **Repositories:** Added a new fetchAdvancedDetails function in the PlacesRepository interface (its implementation is in the GooglePlacesRepositoryFile).

## Checklist

- [x] This PR resolves #194.
- [x] Tests have been added for new functionality.
- [x] Documentation has been updated.

##  Testing

- **Manual Testing:**
    - [x] Tested on emulator / physical device.
- **Unit Tests**
    - [x] Added units tests for this

##  Related Issues/Tickets

Closes #194 
Opened #202 to inform user when fetching for the rest of the details 

## 💡 Additional Context

Add any other context or details you think reviewers should know about.

### CODE REVIEW

File: app/src/main/java/com/android/voyageur/model/place/GooglePlacesRepository.kt [hunk 1]
```diff
@@ -108,28 +107,13 @@ class GooglePlacesRepository(private val placesClient: PlacesClient) : PlacesRep
...
-                  .addOnSuccessListener { fetchPhotoResponse ->
-                    val bitmap = fetchPhotoResponse.bitmap.asImageBitmap()
-                    bitmaps.add(bitmap)
-                  }
-                  .addOnFailureListener { exception ->
-                    Log.e("PlacesRepository", "Failed to fetch photo for $placeId", exception)
-                  }
-            }
+            val bitmaps = emptyList<ImageBitmap>()
             places.add(CustomPlace(place, bitmaps))
```
Comment (g0g05arui) [inline app/src/main/java/com/android/voyageur/model/place/GooglePlacesRepository.kt:116]: maybe now we don't need a custom place out of the box / we don't require the images(bitmaps) at this steps as they will get filled later.

**Review by g0g05arui — COMMENTED** [review]
I see that the image loading is a bit unreliable, there are instances where the image doesnt display corectly ( isnt fetched in time ). You should add a loader that waits until every image / property is fetched.

File: app/src/main/java/com/android/voyageur/model/place/GooglePlacesRepository.kt (hunk 1 above)
Comment (apana03) [reply app/src/main/java/com/android/voyageur/model/place/GooglePlacesRepository.kt:116]: I think we will need the data class when we support adding places to a trip, in order to also display photos there. This class would allow to store the images and not fetch them each time.

Comment (g0g05arui) [reply app/src/main/java/com/android/voyageur/model/place/GooglePlacesRepository.kt:116]: Hmm, good point. We should talk about this in the next standup, maybe there is no use for the images, but just in case keep it like this and we'll see in the future if we need to remove them or not. Thanks for the quick reply and great work!

**Comment by apana03** [comment]
> I see that the image loading is a bit unreliable, there are instances where the image doesnt display corectly ( isnt fetched in time ). You should add a loader that waits until every image / property is fetched.

Also noticed that, this is due to the fact that we don't fetch the images right away from the search screen but only when selecting a place, opened #202 to add a loading functionality.

File: app/src/main/java/com/android/voyageur/model/place/GooglePlacesRepository.kt (hunk 1 above)
Comment (g0g05arui) [reply app/src/main/java/com/android/voyageur/model/place/GooglePlacesRepository.kt:116]: However, maybe it would be beneficial to get the line coverage above 80%. I think the view model tests could be updated a bit.

Comment (apana03) [reply app/src/main/java/com/android/voyageur/model/place/GooglePlacesRepository.kt:116]: Yes forgot to update the PlacesViewModel tests, tx for catching that :)

**Comment by g0g05arui** [comment]
Everything seems fin now. Approved!

**Review by g0g05arui — APPROVED** [review]
